session_name: default
start_directory: ~/
windows:
    - window_name: scratch
      start_directory: ~/src/github.com/bitwalker
      focus: true
      layout: even-horizontal
      panes:
          - pane
    - window_name: emacs
      start_directory: ~/.emacs.d
      layout: even-horizontal
      panes:
          - pane
          - shell_command:
              - cd ~/src/github.com/bitwalker/dotfiles/.config/doom
    - window_name: oss
      start_directory: ~/src/github.com/bitwalker
      layout: even-horizontal
      panes:
          - pane
    - window_name: wasm
      layout: even-horizontal
      start_directory: ~/src/github.com/bitwalker/lumen
      panes:
          - pane
          - pane
    - window_name: otp
      layout: even-horizontal
      start_directory: ~/src/github.com/bitwalker/otp
      panes:
          - pane
