session_name: default
start_directory: ~/
windows:
    - window_name: scratch
      start_directory: ~/src/github.com/bitwalker
      focus: true
      layout: even-vertical
      panes:
          - focus: true
    - window_name: emacs
      start_directory: ~/.emacs.d
      layout: even-vertical
      panes:
          - focus: true
          - shell_command:
              - cd ~/src/github.com/bitwalker/dotfiles/.config/doom
    - window_name: oss
      start_directory: ~/src/github.com/bitwalker
      layout: even-vertical
      panes:
          - focus: true
    - window_name: wasm
      layout: even-vertical
      start_directory: ~/src/github.com/bitwalker/lumen
      panes:
          - focus: true
          - shell_command:
              - cd ~/src/github.com/bitwalker/lumen
