session_name: default
start_directory: ~/
windows:
    - window_name: scratch
      start_directory: ~/src/github.com/bitwalker
      focus: true
      layout: main-vertical
      panes:
          - focus: true
    - window_name: emacs
      start_directory: ~/.emacs.d
      layout: main-vertical
      panes:
          - focus: true
          - shell_command:
              - cd ~/src/github.com/bitwalker/dotfiles/.config/doom
    - window_name: book
      start_directory: ~/src/github.com/bitwalker/elixir_alchemy
      layout: main-vertical
      panes:
          - focus: true
            shell_command:
                - cd Book
          - shell_command:
                - cd Book
    - window_name: sirloin
      layout: main-vertical
      panes:
          - focus: true
    - window_name: distillery
      start_directory: ~/src/github.com/bitwalker/distillery
      layout: main-vertical
      panes:
          - focus: true
          - shell_command:
              - cd ~/src/github.com/bitwalker/distillery-test
