session_name: default
start_directory: ~/
windows:
    - window_name: scratch
      start_directory: ~/src/github.com/bitwalker
      focus: true
      layout: even-horizontal
      panes:
          - pane
    - window_name: dotfiles
      start_directory: ~/src/github.com/bitwalker/dotfiles
      layout: even-horizontal
      panes:
          - pane
    - window_name: emacs.d
      start_directory: ~/.emacs.d
      layout: even-horizontal
      panes:
          - pane
          - shell_command:
              - cd ~/src/github.com/bitwalker/dotfiles/.config/doom
    - window_name: emacs
      start_directory: ~/src/github.com/bitwalker
      layout: even-horizontal
      panes:
          - shell_command:
              - emacsclient -a '' .
    - window_name: lumen
      layout: even-horizontal
      start_directory: ~/src/github.com/bitwalker/lumen
      panes:
          - pane
          - shell_command:
              - cd ~/src/github.com/bitwalker/eir
    - window_name: llvm
      layout: even-horizontal
      start_directory: ~/src/github.com/bitwalker/llvm-project
      panes:
          - pane
          - pane
